name: generate animation

on:
  schedule:
    - cron: '0 */12 * * *'

  workflow_dispatch:

  push:
    branches:
      - output

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate silly-contribution-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/silly-contribution-snake.svg
            assets/silly-contribution-snake-dark.svg?palette=github-dark

      - name: push silly-contribution-snake.svg to main branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
